# Generated by Django 6.1 on 2026-08-31 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(help_text='Detailed description of the issue', max_length=5000),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.FloatField(help_text='Latitude must be between -90 and 90', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.FloatField(help_text='Longitude must be between -180 and 180', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
